package com.aynclub.akilleffect.utils.inventory;

public enum Heads {
    HEART("Mjg2OWJkZDlhOGY3N2VlZmY3NWQ4ZjY3ZWQwMzIyYmQ5YzE2ZGQ0OTQ5NzIzMTRlZDcwN2RkMTBhMzEzOWE1OCJ9fX0="),
    SQUID("MDE0MzNiZTI0MjM2NmFmMTI2ZGE0MzRiODczNWRmMWViNWIzY2IyY2VkZTM5MTQ1OTc0ZTljNDgzNjA3YmFjIn19fQ=="),
    WAVE("YmY5ZTMwZTNhMGQzYzg3YjNmMTRkNjFhYWY5OWY5YzE4MWNmOGVmNDQwOTdjMzE2MTI2NmY3OTI0NzJhNjU5OSJ9fX0="),
    DEVIL("OWRhMzkyNjllZjQ1ZjgyNWVjNjFiYjRmOGFhMDliZDNjZjA3OTk2ZmI2ZmFjMzM4YTZlOTFkNjY5OWFlNDI1In19fQ=="),
    FLAME("MjE3MDg1NzRlN2U5YTZhNzZjOWFhODIxNDc5N2IxYWMzODk1MDY4OWVmOWNkZGExOGQ1MDM2MjM5OGI2MTAxZCJ9fX0="),
    FIREWORK("MzAyZjQ4ZjM0ZDIyZGVkNzQwNGY3NmU4YTEzMmFmNWQ3OTE5YzhkY2Q1MWRmNmU3YTg1ZGRmYWM4NWFiIn19fQ=="),
    SOUP("NzBmMTc0OWZiMjA0ZDNjOTUyNGQwNDMxMjNkZGU5YTFjNThkMjg2NWE3YWRiNzkwMTk5MWU4ZGU4MWQifX19"),
    TORNADO("Nzk2MGRhMjYxMjZiYzAyYWU4ODIzMTAxMDVjNzY1ZTEwNjk0NzkyZTY3NzE2ZGQ1MGJhZmVjMTkwZmViZWNmMyJ9fX0="),
    REDSTONE("YmI3OGZhNWRlZmU3MmRlYmNkOWM3NmFiOWY0ZTExNDI1MDQ3OWJiOWI0NGY0Mjg4N2JiZjZmNzM4NjEyYiJ9fX0="),
    ANGRY("NGZiOTdiMTdjNjM5NTM5MjY1OGYzMjcxOGFhNDZiZWZhMWMzMWQzNTcyNjUxYzMwZjdkMmJmM2I5M2Y2ZWFkOSJ9fX0="),
    Blacksoup("ODFmNTRkMTI4NjNkY2RhNjg2YmNiZGM5NzQ3NzFkZDUyYjU3MDE5OWIxOTRmNjBiOGNlZTIzZDRiYTEwOGUzYiJ9fX0="),
    DIAMOND("NzM4YzUyMmE1YjIyMzViNDAwZTgyN2NmOTYxNTU1YTI2NGZhMmEyNTJlZDBlMzNkMWM3YzczN2ZlOGZjZDI3YyJ9fX0="),
    Snow("ZTBmZDEzYTk2YTgyNDMwNjIxYTY1ZWE5N2U4OTgxOWNhMGI2OGMwMzQyNTMwMjVkYTA0MjhiYmNhZDQzZmQ2MyJ9fX0="),
    TNT("ZjhlNmJkZmFlNmI3MWRkMmExNTc4NTExZjk4N2Q1OTJjMGJhY2I4Yzc5M2M2YWJkMDU4YzdhZjU4NzJkZDQxYyJ9fX0="),
    Fire("Nzk1YTdhNjdmN2E0YjM4ZjgyN2YxYmNhODBlNjFmNDg2MDZiNjljZTVmNjQzNDQxMmJiZmQ4YTU3NjU2YWQyZCJ9fX0="),
    Lightning("YzQ2NWMxMjE5NThjMDUyMmUzZGNjYjNkMTRkNjg2MTJkNjMxN2NkMzgwYjBlNjQ2YjYxYjc0MjBiOTA0YWYwMiJ9fX0="),
    Redsoup("ODIxNDliZTJlNmM0MmMwYWNhNjM0ZTkyMmYyZTZlY2M3Y2JiZmFkZDRmNmQzNDBmYjQ2NzIxZDQzOGY5YmUyZSJ9fX0=");
    private final String texture;

    Heads(String texture) {
        this.texture = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUv" + texture;
    }

    public String getTexture() {
        return texture;
    }
}
